apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
        - args:
            - sh
            - -c
            - sleep 3; bundle exec ruby app.rb -o0.0.0.0
          env:
            - name: POSTGRES_DB
              value: seckun
            - name: POSTGRES_HOST
              value: 172.17.0.3
            - name: POSTGRES_PASSWORD
              value: XXXXXXXXXXXXXXXXXXXXXXX
            - name: POSTGRES_USER
              value: postgres
            - name: WAIT_HOSTS
              value: 172.17.0.3:5432
          image: seckun:app
          name: app
          ports:
            - containerPort: 4567
          resources: {}
      restartPolicy: Always
status: {}
